INSERT INTO roles (name, description)
VALUES
  ('admin', 'Full system administrator with unrestricted access.'),
  ('manager', 'Store manager with access to operational management features.'),
  ('cashier', 'Point-of-sale cashier with sales and customer access.'),
  ('inventory_manager', 'Inventory manager with product, stock, and purchasing access.')
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  updated_at = CURRENT_TIMESTAMP;

WITH permissions_seed (name, module, action) AS (
  VALUES
    ('users:read', 'users', 'read'),
    ('users:create', 'users', 'create'),
    ('users:update', 'users', 'update'),
    ('users:deactivate', 'users', 'deactivate'),
    ('roles:read', 'roles', 'read'),
    ('roles:create', 'roles', 'create'),
    ('roles:update', 'roles', 'update'),
    ('roles:delete', 'roles', 'delete'),
    ('permissions:read', 'permissions', 'read'),
    ('permissions:assign', 'permissions', 'assign'),
    ('branches:read', 'branches', 'read'),
    ('branches:create', 'branches', 'create'),
    ('branches:update', 'branches', 'update'),
    ('branches:delete', 'branches', 'delete'),
    ('products:read', 'products', 'read'),
    ('products:create', 'products', 'create'),
    ('products:update', 'products', 'update'),
    ('products:delete', 'products', 'delete'),
    ('categories:read', 'categories', 'read'),
    ('categories:create', 'categories', 'create'),
    ('categories:update', 'categories', 'update'),
    ('categories:delete', 'categories', 'delete'),
    ('suppliers:read', 'suppliers', 'read'),
    ('suppliers:create', 'suppliers', 'create'),
    ('suppliers:update', 'suppliers', 'update'),
    ('suppliers:delete', 'suppliers', 'delete'),
    ('customers:read', 'customers', 'read'),
    ('customers:create', 'customers', 'create'),
    ('customers:update', 'customers', 'update'),
    ('customers:delete', 'customers', 'delete'),
    ('inventory:read', 'inventory', 'read'),
    ('inventory:adjust', 'inventory', 'adjust'),
    ('inventory:transfer', 'inventory', 'transfer'),
    ('sales:read', 'sales', 'read'),
    ('sales:create', 'sales', 'create'),
    ('sales:void', 'sales', 'void'),
    ('sales:refund', 'sales', 'refund'),
    ('purchases:read', 'purchases', 'read'),
    ('purchases:create', 'purchases', 'create'),
    ('purchases:update', 'purchases', 'update'),
    ('purchases:cancel', 'purchases', 'cancel'),
    ('reports:read', 'reports', 'read'),
    ('reports:export', 'reports', 'export')
)
INSERT INTO permissions (name, module, action)
SELECT name, module, action
FROM permissions_seed
ON CONFLICT (name) DO UPDATE SET
  module = EXCLUDED.module,
  action = EXCLUDED.action,
  updated_at = CURRENT_TIMESTAMP;

WITH role_permission_seed (role_name, permission_name) AS (
  VALUES
    ('admin', 'users:read'),
    ('admin', 'users:create'),
    ('admin', 'users:update'),
    ('admin', 'users:deactivate'),
    ('admin', 'roles:read'),
    ('admin', 'roles:create'),
    ('admin', 'roles:update'),
    ('admin', 'roles:delete'),
    ('admin', 'permissions:read'),
    ('admin', 'permissions:assign'),
    ('admin', 'branches:read'),
    ('admin', 'branches:create'),
    ('admin', 'branches:update'),
    ('admin', 'branches:delete'),
    ('admin', 'products:read'),
    ('admin', 'products:create'),
    ('admin', 'products:update'),
    ('admin', 'products:delete'),
    ('admin', 'categories:read'),
    ('admin', 'categories:create'),
    ('admin', 'categories:update'),
    ('admin', 'categories:delete'),
    ('admin', 'suppliers:read'),
    ('admin', 'suppliers:create'),
    ('admin', 'suppliers:update'),
    ('admin', 'suppliers:delete'),
    ('admin', 'customers:read'),
    ('admin', 'customers:create'),
    ('admin', 'customers:update'),
    ('admin', 'customers:delete'),
    ('admin', 'inventory:read'),
    ('admin', 'inventory:adjust'),
    ('admin', 'inventory:transfer'),
    ('admin', 'sales:read'),
    ('admin', 'sales:create'),
    ('admin', 'sales:void'),
    ('admin', 'sales:refund'),
    ('admin', 'purchases:read'),
    ('admin', 'purchases:create'),
    ('admin', 'purchases:update'),
    ('admin', 'purchases:cancel'),
    ('admin', 'reports:read'),
    ('admin', 'reports:export'),
    ('manager', 'users:read'),
    ('manager', 'users:create'),
    ('manager', 'users:update'),
    ('manager', 'branches:read'),
    ('manager', 'branches:create'),
    ('manager', 'branches:update'),
    ('manager', 'products:read'),
    ('manager', 'products:create'),
    ('manager', 'products:update'),
    ('manager', 'products:delete'),
    ('manager', 'categories:read'),
    ('manager', 'categories:create'),
    ('manager', 'categories:update'),
    ('manager', 'categories:delete'),
    ('manager', 'suppliers:read'),
    ('manager', 'suppliers:create'),
    ('manager', 'suppliers:update'),
    ('manager', 'suppliers:delete'),
    ('manager', 'customers:read'),
    ('manager', 'customers:create'),
    ('manager', 'customers:update'),
    ('manager', 'customers:delete'),
    ('manager', 'inventory:read'),
    ('manager', 'inventory:adjust'),
    ('manager', 'inventory:transfer'),
    ('manager', 'sales:read'),
    ('manager', 'sales:create'),
    ('manager', 'sales:void'),
    ('manager', 'sales:refund'),
    ('manager', 'purchases:read'),
    ('manager', 'purchases:create'),
    ('manager', 'purchases:update'),
    ('manager', 'purchases:cancel'),
    ('manager', 'reports:read'),
    ('manager', 'reports:export'),
    ('cashier', 'products:read'),
    ('cashier', 'customers:read'),
    ('cashier', 'customers:create'),
    ('cashier', 'customers:update'),
    ('cashier', 'inventory:read'),
    ('cashier', 'sales:read'),
    ('cashier', 'sales:create'),
    ('cashier', 'reports:read'),
    ('inventory_manager', 'products:read'),
    ('inventory_manager', 'products:create'),
    ('inventory_manager', 'products:update'),
    ('inventory_manager', 'categories:read'),
    ('inventory_manager', 'categories:create'),
    ('inventory_manager', 'categories:update'),
    ('inventory_manager', 'suppliers:read'),
    ('inventory_manager', 'suppliers:create'),
    ('inventory_manager', 'suppliers:update'),
    ('inventory_manager', 'inventory:read'),
    ('inventory_manager', 'inventory:adjust'),
    ('inventory_manager', 'inventory:transfer'),
    ('inventory_manager', 'purchases:read'),
    ('inventory_manager', 'purchases:create'),
    ('inventory_manager', 'purchases:update'),
    ('inventory_manager', 'purchases:cancel'),
    ('inventory_manager', 'reports:read')
)
INSERT INTO role_permissions (role_id, permission_id)
SELECT roles.id, permissions.id
FROM role_permission_seed
JOIN roles ON roles.name = role_permission_seed.role_name
JOIN permissions ON permissions.name = role_permission_seed.permission_name
ON CONFLICT (role_id, permission_id) DO UPDATE SET
  updated_at = CURRENT_TIMESTAMP;
